runtime: nodejs20
instance_class: F1
automatic_scaling:
  max_instances: 1
env_variables:
  PUBLIC_SUPABASE_PROJECT_URL: 'https://yhoafujbjlmwsopsyjlb.supabase.co'
  PUBLIC_SUPABASE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlob2FmdWpiamxtd3NvcHN5amxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE2ODg4MjE5NzAsImV4cCI6MjAwNDM5Nzk3MH0.kqKnUhi9bM-scY6gROr1mHMuGQSq2MHpvBxAzmudq7U'
  PUBLIC_SERVICE_KEY: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlob2FmdWpiamxtd3NvcHN5amxiIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY4ODgyMTk3MCwiZXhwIjoyMDA0Mzk3OTcwfQ.GBhUCA2Vv3PP3IZmoKW2exEVn-e_8x9E3cyo2bcec0I'
  HASH_RESERVED: '1b0459150b32937caf6492c426dbda4cd406ca3b9bf8334536abfd442054bbea29df46676e941592b1fc82ec201e83c02ff62fe509ac6d6dc8dffc967741caac'
